# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SECRET_KEY: 'django-insecure-*_1d4=wk3*j(_o00dg$7)33$psem@7^7l&umaw%sqt9d9hvnv%'
  ALLOWED_HOSTS: '*'
    
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Set up virtual environment and install dependencies'

- script: |
    if [ -z "$SECRET_KEY" ]; then echo "SECRET_KEY is missing 😬"; else echo "SECRET_KEY is set ✅"; fi
    # source venv/bin/activate
    # python manage.py migrate --noinput
    # python manage.py collectstatic --noinput
  displayName: 'Django migrations & collectstatic'
  env:
    SECRET_KEY: $(SECRET_KEY)  # Use same name as expected by decouple
    DEBUG: False
    ALLOWED_HOSTS: $(ALLOWED_HOSTS)
