name: Django CI/CD to Azure Web App

on:
  push:
    branches:
      - main  # or 'master' or any branch you prefer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Create and start virtual environment
      run: |
          python -m venv venv
          source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt

    - name: Django migrations & collectstatic
      run: |
        python manage.py migrate --noinput
        python manage.py collectstatic --noinput
      env:
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}

    # - name: (Optional) Run Django tests
    #   run: |
    #       python manage.py test

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C6A71136DDCF415FA965C045A9F81550 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AAE3B45207A141FFBCE82349FD33CFC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F07DF7E3C13140199621CC285F416988 }}
     
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'phora-model-backend-api'
          slot-name: 'Production'
          package: './backend'



